<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Template.Application\Template.Application.csproj" />
    <ProjectReference Include="..\Template.Domain\Template.Domain.csproj" />
    <ProjectReference Include="..\Template.Persistence\Template.Persistence.csproj" />
  </ItemGroup>

</Project>
