// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParkingSystem.Data;

#nullable disable

namespace ParkingSystem.Data.Migrations
{
    [DbContext(typeof(ParkingDbContext))]
    [Migration("20260928011546_AddReservationGuards")]
    partial class AddReservationGuards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParkingSystem.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValueJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValueJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ParkingLotId", "CreatedAt");

                    b.ToTable("AuditLogs", t =>
                        {
                            t.HasCheckConstraint("CK_AuditLogs_ActorType", "\"ActorType\" IN (0,1,2,3,4)");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuestOtpChallengeId")
                        .HasColumnType("uuid");

                    b.Property<string>("GuestPhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("HoldExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedPlate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlateSnapshot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("QuotedTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("GuestOtpChallengeId")
                        .IsUnique()
                        .HasFilter("\"GuestOtpChallengeId\" IS NOT NULL");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("ParkingLotId", "StartAt");

                    b.HasIndex("Status", "HoldExpiresAt");

                    b.ToTable("Bookings", t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_Amount", "\"QuotedTotal\" >= 0");

                            t.HasCheckConstraint("CK_Bookings_Guest", "(\"UserId\" IS NULL AND \"GuestPhoneNumber\" IS NOT NULL AND \"GuestOtpChallengeId\" IS NOT NULL) OR (\"UserId\" IS NOT NULL AND \"VehicleId\" IS NOT NULL AND \"GuestOtpChallengeId\" IS NULL)");

                            t.HasCheckConstraint("CK_Bookings_Interval", "\"StartAt\" < \"EndAt\"");

                            t.HasCheckConstraint("CK_Bookings_Mode", "\"Mode\" IN (0,1)");

                            t.HasCheckConstraint("CK_Bookings_Plate", "\"NormalizedPlate\" ~ '^[A-Z0-9]+$'");

                            t.HasCheckConstraint("CK_Bookings_Status", "\"Status\" IN (0,1,2,3,4,5,6)");

                            t.HasCheckConstraint("CK_Bookings_VehicleType", "\"VehicleType\" IN (0,1,2)");

                            t.HasCheckConstraint("CK_Bookings_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.CameraEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParkingSlotId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("ParkingSlotId", "ParkingLotId");

                    b.HasIndex("ParkingLotId", "CameraId", "ExternalEventId")
                        .IsUnique();

                    b.ToTable("CameraEvents", t =>
                        {
                            t.HasCheckConstraint("CK_CameraEvents_EventType", "\"EventType\" IN (0,1,2,3,4)");

                            t.HasCheckConstraint("CK_CameraEvents_ReviewStatus", "\"ReviewStatus\" IN (0,1,2,3)");

                            t.HasCheckConstraint("CK_Camera_Confidence", "\"Confidence\" IS NULL OR \"Confidence\" BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.EntranceExit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GateType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId", "Code")
                        .IsUnique();

                    b.ToTable("EntranceExits", t =>
                        {
                            t.HasCheckConstraint("CK_EntranceExits_GateType", "\"GateType\" IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.FacilityStaffAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("ActiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CanManageStaffAssignments")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("ParkingLotId", "UserId");

                    b.ToTable("StaffAssignments", t =>
                        {
                            t.HasCheckConstraint("CK_Assignments_Delegation", "NOT \"CanManageStaffAssignments\" OR \"Role\" = 1");

                            t.HasCheckConstraint("CK_Assignments_Period", "\"ActiveTo\" IS NULL OR \"ActiveTo\" > \"ActiveFrom\"");

                            t.HasCheckConstraint("CK_StaffAssignments_Role", "\"Role\" IN (0,1)");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.MapObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("MapVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ObjectType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParkingLevelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParkingSlotId")
                        .HasColumnType("uuid");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision");

                    b.Property<double>("PositionZ")
                        .HasColumnType("double precision");

                    b.Property<double>("RotationX")
                        .HasColumnType("double precision");

                    b.Property<double>("RotationY")
                        .HasColumnType("double precision");

                    b.Property<double>("RotationZ")
                        .HasColumnType("double precision");

                    b.Property<double>("ScaleX")
                        .HasColumnType("double precision");

                    b.Property<double>("ScaleY")
                        .HasColumnType("double precision");

                    b.Property<double>("ScaleZ")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MapVersionId", "ParkingLotId");

                    b.HasIndex("MapVersionId", "ParkingSlotId")
                        .IsUnique()
                        .HasFilter("\"ParkingSlotId\" IS NOT NULL");

                    b.HasIndex("ParkingLevelId", "ParkingLotId");

                    b.HasIndex("ParkingSlotId", "ParkingLotId");

                    b.ToTable("MapObjects", t =>
                        {
                            t.HasCheckConstraint("CK_MapObjects_ObjectType", "\"ObjectType\" IN (0,1,2,3,4,5,6,7,8,9,10)");

                            t.HasCheckConstraint("CK_MapObjects_Scale", "\"ScaleX\" > 0 AND \"ScaleY\" > 0 AND \"ScaleZ\" > 0");

                            t.HasCheckConstraint("CK_MapObjects_Slot", "(\"ObjectType\" = 0) = (\"ParkingSlotId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.MapVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 1");

                    b.HasIndex("ParkingLotId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("MapVersions", t =>
                        {
                            t.HasCheckConstraint("CK_MapVersions_Number", "\"VersionNumber\" > 0");

                            t.HasCheckConstraint("CK_MapVersions_Status", "\"Status\" IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Recipient")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId", "ReadAt");

                    b.ToTable("Notifications", t =>
                        {
                            t.HasCheckConstraint("CK_Notifications_Channel", "\"Channel\" IN (0,1,2)");

                            t.HasCheckConstraint("CK_Notifications_Status", "\"Status\" IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.OperatingHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<TimeOnly?>("ClosesAt")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("ClosesNextDay")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpen24Hours")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("OpensAt")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("OperatingHours", t =>
                        {
                            t.HasCheckConstraint("CK_Hours_Interval", "((\"IsClosed\" <> \"IsOpen24Hours\") AND \"OpensAt\" IS NULL AND \"ClosesAt\" IS NULL AND NOT \"ClosesNextDay\") OR (NOT \"IsClosed\" AND NOT \"IsOpen24Hours\" AND \"OpensAt\" IS NOT NULL AND \"ClosesAt\" IS NOT NULL AND ((NOT \"ClosesNextDay\" AND \"OpensAt\" < \"ClosesAt\") OR (\"ClosesNextDay\" AND \"ClosesAt\" < \"OpensAt\")))");

                            t.HasCheckConstraint("CK_OperatingHours_DayOfWeek", "\"DayOfWeek\" IN (0,1,2,3,4,5,6)");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedPlate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber", "Purpose", "CreatedAt");

                    b.ToTable("OtpChallenges", t =>
                        {
                            t.HasCheckConstraint("CK_OtpChallenges_Purpose", "\"Purpose\" IN (0)");

                            t.HasCheckConstraint("CK_Otp_Attempts", "\"MaxAttempts\" > 0 AND \"FailedAttempts\" BETWEEN 0 AND \"MaxAttempts\"");

                            t.HasCheckConstraint("CK_Otp_Consumption", "\"ConsumedAt\" IS NULL OR (\"VerifiedAt\" IS NOT NULL AND \"ConsumedAt\" >= \"VerifiedAt\")");

                            t.HasCheckConstraint("CK_Otp_Expiry", "\"ExpiresAt\" > \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CameraEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParkingSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReportedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resolution")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("BookingId", "ParkingLotId");

                    b.HasIndex("CameraEventId", "ParkingLotId");

                    b.HasIndex("ParkingSessionId", "ParkingLotId");

                    b.ToTable("ParkingIssues", t =>
                        {
                            t.HasCheckConstraint("CK_ParkingIssues_Status", "\"Status\" IN (0,1,2,3,4)");

                            t.HasCheckConstraint("CK_ParkingIssues_Type", "\"Type\" IN (0,1,2,3,4,5,6)");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("LevelType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId", "Code")
                        .IsUnique();

                    b.ToTable("ParkingLevels", t =>
                        {
                            t.HasCheckConstraint("CK_ParkingLevels_LevelType", "\"LevelType\" IN (0,1,2,3,4,5)");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("MapThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ParkingLots", t =>
                        {
                            t.HasCheckConstraint("CK_Lots_Coordinates", "\"Latitude\" BETWEEN -90 AND 90 AND \"Longitude\" BETWEEN -180 AND 180");

                            t.HasCheckConstraint("CK_ParkingLots_Status", "\"Status\" IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AllowGuestBookings")
                        .HasColumnType("boolean");

                    b.Property<int?>("CancellationRefundCutoffMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CancellationRefundPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("ChargeOvertime")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("EarlyArrivalMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("ExitGraceMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("LateArrivalMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumBookingMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumBookingMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentHoldMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("QrLifetimeMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("RefundUnusedTimeOnEarlyExit")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireFullPrepayment")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId")
                        .IsUnique();

                    b.ToTable("ParkingPolicies", t =>
                        {
                            t.HasCheckConstraint("CK_Policy_Durations", "\"PaymentHoldMinutes\" > 0 AND \"MinimumBookingMinutes\" > 0 AND \"MaximumBookingMinutes\" >= \"MinimumBookingMinutes\"");

                            t.HasCheckConstraint("CK_Policy_OptionalWindows", "(\"EarlyArrivalMinutes\" IS NULL OR \"EarlyArrivalMinutes\" >= 0) AND (\"LateArrivalMinutes\" IS NULL OR \"LateArrivalMinutes\" >= 0) AND (\"QrLifetimeMinutes\" IS NULL OR \"QrLifetimeMinutes\" > 0) AND (\"ExitGraceMinutes\" IS NULL OR \"ExitGraceMinutes\" >= 0)");

                            t.HasCheckConstraint("CK_Policy_Refund", "(\"CancellationRefundCutoffMinutes\" IS NULL AND \"CancellationRefundPercent\" IS NULL) OR (\"CancellationRefundCutoffMinutes\" IS NOT NULL AND \"CancellationRefundCutoffMinutes\" >= 0 AND \"CancellationRefundPercent\" IS NOT NULL AND \"CancellationRefundPercent\" BETWEEN 0 AND 100)");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("EnteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExitRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FeeCalculatedThrough")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("NormalizedPlate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParkingSlotId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlateSnapshot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasFilter("\"BookingId\" IS NOT NULL");

                    b.HasIndex("NormalizedPlate")
                        .IsUnique()
                        .HasFilter("\"Status\" IN (0,1)");

                    b.HasIndex("ParkingLotId");

                    b.HasIndex("ParkingSlotId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN (0,1)");

                    b.HasIndex("VehicleId");

                    b.HasIndex("BookingId", "ParkingLotId")
                        .IsUnique();

                    b.HasIndex("ParkingSlotId", "ParkingLotId");

                    b.ToTable("ParkingSessions", t =>
                        {
                            t.HasCheckConstraint("CK_ParkingSessions_Status", "\"Status\" IN (0,1,2)");

                            t.HasCheckConstraint("CK_ParkingSessions_VehicleType", "\"VehicleType\" IN (0,1,2)");

                            t.HasCheckConstraint("CK_ParkingSessions_Version", "\"Version\" > 0");

                            t.HasCheckConstraint("CK_Sessions_Exit", "(\"Status\" = 2 AND \"ExitedAt\" IS NOT NULL AND \"ExitedAt\" >= \"EnteredAt\") OR (\"Status\" IN (0,1) AND \"ExitedAt\" IS NULL)");

                            t.HasCheckConstraint("CK_Sessions_Fee", "\"FinalFee\" IS NULL OR \"FinalFee\" >= 0");

                            t.HasCheckConstraint("CK_Sessions_Plate", "\"NormalizedPlate\" ~ '^[A-Z0-9]+$'");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("DistanceToExitMeters")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("LengthMeters")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("OperationalStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("SupportedVehicleTypes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<decimal?>("WidthMeters")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId", "Code")
                        .IsUnique();

                    b.HasIndex("ZoneId", "ParkingLotId");

                    b.ToTable("ParkingSlots", t =>
                        {
                            t.HasCheckConstraint("CK_ParkingSlots_OperationalStatus", "\"OperationalStatus\" IN (0,1,2)");

                            t.HasCheckConstraint("CK_ParkingSlots_Version", "\"Version\" > 0");

                            t.HasCheckConstraint("CK_Slots_Dimensions", "(\"WidthMeters\" IS NULL OR \"WidthMeters\" > 0) AND (\"LengthMeters\" IS NULL OR \"LengthMeters\" > 0) AND (\"DistanceToExitMeters\" IS NULL OR \"DistanceToExitMeters\" >= 0)");

                            t.HasCheckConstraint("CK_Slots_VehicleTypes", "cardinality(\"SupportedVehicleTypes\") > 0 AND \"SupportedVehicleTypes\" <@ ARRAY[0,1,2] AND array_position(\"SupportedVehicleTypes\", NULL) IS NULL");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingSlotFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ParkingSlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SlotFeatureId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SlotFeatureId");

                    b.HasIndex("ParkingSlotId", "SlotFeatureId")
                        .IsUnique();

                    b.ToTable("ParkingSlotFeatures");
                });

            modelBuilder.Entity("ParkingSystem.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CashConfirmedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParkingSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("CashConfirmedByUserId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ParkingSessionId");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount", "\"Amount\" >= 0");

                            t.HasCheckConstraint("CK_Payments_Cash", "\"Method\" <> 1 OR \"Status\" NOT IN (1,3,4) OR \"CashConfirmedByUserId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Payments_Method", "\"Method\" IN (0,1)");

                            t.HasCheckConstraint("CK_Payments_Owner", "(\"BookingId\" IS NULL) <> (\"ParkingSessionId\" IS NULL)");

                            t.HasCheckConstraint("CK_Payments_Status", "\"Status\" IN (0,1,2,3,4)");

                            t.HasCheckConstraint("CK_Payments_Type", "\"Type\" IN (0,1,2)");

                            t.HasCheckConstraint("CK_Payments_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequestReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResponseCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("Provider", "EventKey")
                        .IsUnique()
                        .HasFilter("\"EventKey\" IS NOT NULL");

                    b.HasIndex("Provider", "ProviderReference")
                        .IsUnique()
                        .HasFilter("\"ProviderReference\" IS NOT NULL");

                    b.HasIndex("Provider", "RequestReference")
                        .IsUnique();

                    b.ToTable("PaymentTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentTransactions_Status", "\"Status\" IN (0,1,2)");

                            t.HasCheckConstraint("CK_PaymentTransactions_Type", "\"Type\" IN (0,1)");

                            t.HasCheckConstraint("CK_Transactions_Amount", "\"Amount\" >= 0");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.PricingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("PricingPlans", t =>
                        {
                            t.HasCheckConstraint("CK_Plans_Period", "\"VersionNumber\" > 0 AND (\"EffectiveTo\" IS NULL OR \"EffectiveTo\" > \"EffectiveFrom\")");

                            t.HasCheckConstraint("CK_PricingPlans_Status", "\"Status\" IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.PricingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PricingPlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RuleType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PricingPlanId", "ParkingLotId");

                    b.HasIndex("ZoneId", "ParkingLotId");

                    b.ToTable("PricingRules", t =>
                        {
                            t.HasCheckConstraint("CK_PricingRules_RuleType", "\"RuleType\" IN (0,1,2,3,4,5,6,7,8,9)");

                            t.HasCheckConstraint("CK_PricingRules_VehicleType", "\"VehicleType\" IN (0,1,2)");

                            t.HasCheckConstraint("CK_Rules_Json", "jsonb_typeof(\"ParametersJson\") = 'object'");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.PricingSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParkingSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PricingPlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("PricingPlanVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ResolvedRulesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId", "ParkingLotId")
                        .IsUnique();

                    b.HasIndex("ParkingSessionId", "ParkingLotId")
                        .IsUnique();

                    b.HasIndex("PricingPlanId", "ParkingLotId");

                    b.ToTable("PricingSnapshots", t =>
                        {
                            t.HasCheckConstraint("CK_Snapshots_Owner", "\"BookingId\" IS NOT NULL OR \"ParkingSessionId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.QRToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NonceHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("NonceHash")
                        .IsUnique();

                    b.ToTable("QRTokens", t =>
                        {
                            t.HasCheckConstraint("CK_QR_Expiry", "\"ExpiresAt\" > \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.SlotFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SlotFeatures");
                });

            modelBuilder.Entity("ParkingSystem.Models.SlotReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParkingSlotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReleaseReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReservedFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReservedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN (0,1)");

                    b.HasIndex("BookingId", "ParkingLotId");

                    b.HasIndex("ParkingSlotId", "ParkingLotId");

                    b.ToTable("SlotReservations", t =>
                        {
                            t.HasCheckConstraint("CK_Reservations_Interval", "\"ReservedFrom\" < \"ReservedUntil\"");

                            t.HasCheckConstraint("CK_SlotReservations_Status", "\"Status\" IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("PhoneVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlatformRole")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("\"PhoneNumber\" IS NOT NULL");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Login", "\"Email\" IS NOT NULL OR \"PhoneNumber\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Users_PlatformRole", "\"PlatformRole\" IN (0,1)");

                            t.HasCheckConstraint("CK_Users_Status", "\"Status\" IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("FuelType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("NormalizedPlate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedPlate")
                        .IsUnique()
                        .HasFilter("\"IsActive\"");

                    b.HasIndex("OwnerUserId")
                        .IsUnique()
                        .HasFilter("\"IsActive\" AND \"IsPrimary\" AND \"OwnerUserId\" IS NOT NULL");

                    b.ToTable("Vehicles", t =>
                        {
                            t.HasCheckConstraint("CK_Vehicles_FuelType", "\"FuelType\" IN (0,1,2,3)");

                            t.HasCheckConstraint("CK_Vehicles_VehicleType", "\"VehicleType\" IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AllocationPriority")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ParkingLevelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLevelId", "Code")
                        .IsUnique();

                    b.HasIndex("ParkingLevelId", "ParkingLotId");

                    b.ToTable("Zones", t =>
                        {
                            t.HasCheckConstraint("CK_Zones_Status", "\"Status\" IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("ParkingSystem.Models.AuditLog", b =>
                {
                    b.HasOne("ParkingSystem.Models.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingSystem.Models.ParkingLot", "ParkingLot")
                        .WithMany()
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("ParkingSystem.Models.Booking", b =>
                {
                    b.HasOne("ParkingSystem.Models.OtpChallenge", "GuestOtpChallenge")
                        .WithMany()
                        .HasForeignKey("GuestOtpChallengeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingSystem.Models.ParkingLot", "ParkingLot")
                        .WithMany()
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingSystem.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GuestOtpChallenge");

                    b.Navigation("ParkingLot");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ParkingSystem.Models.CameraEvent", b =>
                {
                    b.HasOne("ParkingSystem.Models.ParkingLot", "ParkingLot")
                        .WithMany()
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingSystem.Models.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingSystem.Models.ParkingSlot", "ParkingSlot")
                        .WithMany()
                        .HasForeignKey("ParkingSlotId", "ParkingLotId")
                        .HasPrincipalKey("Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParkingLot");

                    b.Navigation("ParkingSlot");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("ParkingSystem.Models.EntranceExit", b =>
                {
                    b.HasOne("ParkingSystem.Models.ParkingLot", "ParkingLot")
                        .WithMany("Gates")
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("ParkingSystem.Models.FacilityStaffAssignment", b =>
                {
                    b.HasOne("ParkingSystem.Models.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingSystem.Models.ParkingLot", "ParkingLot")
                        .WithMany()
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingSystem.Models.User", "User")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("ParkingLot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParkingSystem.Models.MapObject", b =>
                {
                    b.HasOne("ParkingSystem.Models.MapVersion", "MapVersion")
                        .WithMany("Objects")
                        .HasForeignKey("MapVersionId", "ParkingLotId")
                        .HasPrincipalKey("Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingSystem.Models.ParkingLevel", "ParkingLevel")
                        .WithMany()
                        .HasForeignKey("ParkingLevelId", "ParkingLotId")
                        .HasPrincipalKey("Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingSystem.Models.ParkingSlot", "ParkingSlot")
                        .WithMany()
                        .HasForeignKey("ParkingSlotId", "ParkingLotId")
                        .HasPrincipalKey("Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MapVersion");

                    b.Navigation("ParkingLevel");

                    b.Navigation("ParkingSlot");
                });

            modelBuilder.Entity("ParkingSystem.Models.MapVersion", b =>
                {
                    b.HasOne("ParkingSystem.Models.ParkingLot", "ParkingLot")
                        .WithMany()
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("ParkingSystem.Models.Notification", b =>
                {
                    b.HasOne("ParkingSystem.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParkingSystem.Models.OperatingHours", b =>
                {
                    b.HasOne("ParkingSystem.Models.ParkingLot", "ParkingLot")
                        .WithMany("OperatingHours")
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingIssue", b =>
                {
                    b.HasOne("ParkingSystem.Models.ParkingLot", "ParkingLot")
                        .WithMany()
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingSystem.Models.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingSystem.Models.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingSystem.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId", "ParkingLotId")
                        .HasPrincipalKey("Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingSystem.Models.CameraEvent", "CameraEvent")
                        .WithMany()
                        .HasForeignKey("CameraEventId", "ParkingLotId")
                        .HasPrincipalKey("Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingSystem.Models.ParkingSession", "ParkingSession")
                        .WithMany()
                        .HasForeignKey("ParkingSessionId", "ParkingLotId")
                        .HasPrincipalKey("Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("CameraEvent");

                    b.Navigation("ParkingLot");

                    b.Navigation("ParkingSession");

                    b.Navigation("ReportedByUser");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingLevel", b =>
                {
                    b.HasOne("ParkingSystem.Models.ParkingLot", "ParkingLot")
                        .WithMany("Levels")
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingPolicy", b =>
                {
                    b.HasOne("ParkingSystem.Models.ParkingLot", "ParkingLot")
                        .WithOne("Policy")
                        .HasForeignKey("ParkingSystem.Models.ParkingPolicy", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingSession", b =>
                {
                    b.HasOne("ParkingSystem.Models.ParkingLot", "ParkingLot")
                        .WithMany()
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingSystem.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingSystem.Models.Booking", "Booking")
                        .WithOne("Session")
                        .HasForeignKey("ParkingSystem.Models.ParkingSession", "BookingId", "ParkingLotId")
                        .HasPrincipalKey("ParkingSystem.Models.Booking", "Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingSystem.Models.ParkingSlot", "ParkingSlot")
                        .WithMany()
                        .HasForeignKey("ParkingSlotId", "ParkingLotId")
                        .HasPrincipalKey("Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ParkingLot");

                    b.Navigation("ParkingSlot");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingSlot", b =>
                {
                    b.HasOne("ParkingSystem.Models.Zone", "Zone")
                        .WithMany("Slots")
                        .HasForeignKey("ZoneId", "ParkingLotId")
                        .HasPrincipalKey("Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingSlotFeature", b =>
                {
                    b.HasOne("ParkingSystem.Models.ParkingSlot", "ParkingSlot")
                        .WithMany("Features")
                        .HasForeignKey("ParkingSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingSystem.Models.SlotFeature", "SlotFeature")
                        .WithMany("Slots")
                        .HasForeignKey("SlotFeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingSlot");

                    b.Navigation("SlotFeature");
                });

            modelBuilder.Entity("ParkingSystem.Models.Payment", b =>
                {
                    b.HasOne("ParkingSystem.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingSystem.Models.User", "CashConfirmedByUser")
                        .WithMany()
                        .HasForeignKey("CashConfirmedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingSystem.Models.ParkingSession", "ParkingSession")
                        .WithMany("Payments")
                        .HasForeignKey("ParkingSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("CashConfirmedByUser");

                    b.Navigation("ParkingSession");
                });

            modelBuilder.Entity("ParkingSystem.Models.PaymentTransaction", b =>
                {
                    b.HasOne("ParkingSystem.Models.Payment", "Payment")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("ParkingSystem.Models.PricingPlan", b =>
                {
                    b.HasOne("ParkingSystem.Models.ParkingLot", "ParkingLot")
                        .WithMany()
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("ParkingSystem.Models.PricingRule", b =>
                {
                    b.HasOne("ParkingSystem.Models.PricingPlan", "PricingPlan")
                        .WithMany("Rules")
                        .HasForeignKey("PricingPlanId", "ParkingLotId")
                        .HasPrincipalKey("Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingSystem.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId", "ParkingLotId")
                        .HasPrincipalKey("Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PricingPlan");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("ParkingSystem.Models.PricingSnapshot", b =>
                {
                    b.HasOne("ParkingSystem.Models.Booking", "Booking")
                        .WithOne("PricingSnapshot")
                        .HasForeignKey("ParkingSystem.Models.PricingSnapshot", "BookingId", "ParkingLotId")
                        .HasPrincipalKey("ParkingSystem.Models.Booking", "Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingSystem.Models.ParkingSession", "ParkingSession")
                        .WithOne("PricingSnapshot")
                        .HasForeignKey("ParkingSystem.Models.PricingSnapshot", "ParkingSessionId", "ParkingLotId")
                        .HasPrincipalKey("ParkingSystem.Models.ParkingSession", "Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingSystem.Models.PricingPlan", "PricingPlan")
                        .WithMany()
                        .HasForeignKey("PricingPlanId", "ParkingLotId")
                        .HasPrincipalKey("Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ParkingSession");

                    b.Navigation("PricingPlan");
                });

            modelBuilder.Entity("ParkingSystem.Models.QRToken", b =>
                {
                    b.HasOne("ParkingSystem.Models.Booking", "Booking")
                        .WithMany("QrTokens")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("ParkingSystem.Models.SlotReservation", b =>
                {
                    b.HasOne("ParkingSystem.Models.Booking", "Booking")
                        .WithMany("Reservations")
                        .HasForeignKey("BookingId", "ParkingLotId")
                        .HasPrincipalKey("Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingSystem.Models.ParkingSlot", "ParkingSlot")
                        .WithMany()
                        .HasForeignKey("ParkingSlotId", "ParkingLotId")
                        .HasPrincipalKey("Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ParkingSlot");
                });

            modelBuilder.Entity("ParkingSystem.Models.Vehicle", b =>
                {
                    b.HasOne("ParkingSystem.Models.User", "OwnerUser")
                        .WithMany("Vehicles")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("ParkingSystem.Models.Zone", b =>
                {
                    b.HasOne("ParkingSystem.Models.ParkingLevel", "ParkingLevel")
                        .WithMany("Zones")
                        .HasForeignKey("ParkingLevelId", "ParkingLotId")
                        .HasPrincipalKey("Id", "ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingLevel");
                });

            modelBuilder.Entity("ParkingSystem.Models.Booking", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("PricingSnapshot");

                    b.Navigation("QrTokens");

                    b.Navigation("Reservations");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ParkingSystem.Models.MapVersion", b =>
                {
                    b.Navigation("Objects");
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingLevel", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingLot", b =>
                {
                    b.Navigation("Gates");

                    b.Navigation("Levels");

                    b.Navigation("OperatingHours");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingSession", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("PricingSnapshot");
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingSlot", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("ParkingSystem.Models.Payment", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ParkingSystem.Models.PricingPlan", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("ParkingSystem.Models.SlotFeature", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("ParkingSystem.Models.User", b =>
                {
                    b.Navigation("StaffAssignments");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ParkingSystem.Models.Zone", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
