<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.31.1" />
    <PackageReference Include="Grpc.Core.Api" Version="2.76.0" />
    <PackageReference Include="Grpc.Tools" Version="2.76.0" PrivateAssets="All" />
    <Protobuf Include="Protos/v1/*.proto" GrpcServices="Both" />
  </ItemGroup>
</Project>
